name: doctor.hoye
favicon: null
layout_spectrum: 0.8518524100072682
typography_spectrum: 0.6206145270261914
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5612481518182904
  lightness: 0.5931561205070466
  saturation: 0.876099812798202
  rhythmicContrast: 0.11570609547197819
purpose: []
